<template>
    <div>
      <h1>QRCode Generator</h1>
      <p>Genereer hier je QR-code voor een locatie</p>
      <!-- Voeg hier je QR-generator logica toe -->
    </div>
  </template>
  
  <script>
  export default {
    name: "QRCodeGenerator",
    data() {
      return {
        // Voeg hier data voor je component toe, bijvoorbeeld invoervelden
      };
    },
    methods: {
      // Voeg hier je methoden toe, zoals de QR-code generatie logica
    }
  };
  </script>
  
  <style scoped>
  /* Voeg hier je componentstijl toe */
  h1 {
    color: #333;
  }
  </style>
  